# Generated by Django 6.0 on 2025-12-06 00:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id_admin', models.AutoField(primary_key=True, serialize=False)),
                ('nivel_acceso', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='TipoSensor',
            fields=[
                ('id_tipo_sensor', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_tipo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TipoUsuario',
            fields=[
                ('id_tipo_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_tipo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Estacion',
            fields=[
                ('id_estacion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('mantenimiento', 'En mantenimiento'), ('inactiva', 'Inactiva')], default='activa', max_length=20)),
                ('longitud', models.FloatField()),
                ('latitud', models.FloatField()),
                ('admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estaciones', to='core.administrador')),
            ],
        ),
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id_alerta', models.AutoField(primary_key=True, serialize=False)),
                ('nivel', models.CharField(max_length=50)),
                ('mensaje', models.TextField()),
                ('fecha_emision', models.DateField()),
                ('estacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='core.estacion')),
            ],
        ),
        migrations.CreateModel(
            name='Institucion',
            fields=[
                ('id_institucion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('direccion', models.CharField(max_length=250)),
                ('logo', models.CharField(max_length=255)),
                ('color', models.CharField(max_length=20)),
                ('admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instituciones', to='core.administrador')),
            ],
        ),
        migrations.AddField(
            model_name='estacion',
            name='institucion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estaciones', to='core.institucion'),
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id_sensor', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_calibracion', models.DateField()),
                ('responsable_tecnico', models.CharField(max_length=150)),
                ('estacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensores', to='core.estacion')),
                ('tipo_sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensores', to='core.tiposensor')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('tipo_usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.tipousuario')),
            ],
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('estacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultas', to='core.estacion')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultas', to='core.usuario')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
        migrations.AddField(
            model_name='administrador',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='administradores', to='core.usuario'),
        ),
        migrations.CreateModel(
            name='Medicion',
            fields=[
                ('id_medicion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('pm25', models.FloatField(blank=True, null=True)),
                ('pm10', models.FloatField(blank=True, null=True)),
                ('so2', models.FloatField(blank=True, null=True)),
                ('no2', models.FloatField(blank=True, null=True)),
                ('o3', models.FloatField(blank=True, null=True)),
                ('co', models.FloatField(blank=True, null=True)),
                ('temperatura', models.FloatField(blank=True, null=True)),
                ('humedad', models.FloatField(blank=True, null=True)),
                ('velocidad_viento', models.FloatField(blank=True, null=True)),
                ('estacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mediciones', to='core.estacion')),
            ],
            options={
                'ordering': ['-fecha'],
                'unique_together': {('estacion', 'fecha')},
            },
        ),
    ]
